{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ada1b77f-c468-4277-a5ea-1566a154b0a0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44f83404-5a10-4789-b106-79ec9c191d46",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "9a01ab27-ad31-4d2a-a53d-4c9a229a9d6a",
   "metadata": {
    "tags": []
   },
   "source": [
    "### 1. This modolue is to figure out how to run the segmentation for the video and laod the packages"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2df684f9-515e-4d66-aee6-6befceb00632",
   "metadata": {},
   "source": [
    "1. pip install stardist: https://pypi.org/project/stardist/\n",
    "2. pip install tensorflow: https://www.tensorflow.org/install/pip\n",
    "3. please be noted to install the specify tensorflow and pytorch version that work with the same compatible cuda\n",
    "4. This code will take memory to save the segmented volumne for each frame as h5 -->"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "564ca9c6-2236-41dc-8063-6b0e2e3669f3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-27 13:23:05.462890: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n",
      "Tesla P100-PCIE-12GB\n",
      "True\n",
      "2.13.1\n",
      "[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "# from Segmentation import *\n",
    "from Segmentation.Video_seg import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "828084c8-f213-430a-a3b2-97de04c75d34",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "141b4394-6b0a-4409-9dce-fe4e56bffceb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "c89efcda-538d-4ad2-949a-a453c57ea00c",
   "metadata": {},
   "source": [
    "#### 2. Load the model for 3D segmentation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9d205e09-2673-4c84-9892-d70024ff16d3",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "use_gpu:  True\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "base_model.py (149): output path for model already exists, files may be overwritten: /work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/models/stardist\n",
      "2024-03-27 13:23:16.173113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 223 MB memory:  -> device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:03:00.0, compute capability: 6.0\n",
      "2024-03-27 13:23:16.195205: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 223.62MiB (234487808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using default values: prob_thresh=0.5, nms_thresh=0.4.\n",
      "There are 4 registered models for 'StarDist2D':\n",
      "\n",
      "Name                  Alias(es)\n",
      "────                  ─────────\n",
      "'2D_versatile_fluo'   'Versatile (fluorescent nuclei)'\n",
      "'2D_versatile_he'     'Versatile (H&E nuclei)'\n",
      "'2D_paper_dsb2018'    'DSB 2018 (from StarDist 2D paper)'\n",
      "'2D_demo'             None\n",
      "Found model '2D_versatile_fluo' for 'StarDist2D'.\n",
      "Loading network weights from 'weights_best.h5'.\n",
      "Loading thresholds from 'thresholds.json'.\n",
      "Using default values: prob_thresh=0.479071, nms_thresh=0.3.\n"
     ]
    }
   ],
   "source": [
    "model_weights_path = '/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/model_weights/weights_best_42stacks_all.h5'\n",
    "model, model_2D = load_model_3D_and_2D(model_weights_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15b62931-55b0-418a-9fdd-7bc4563d77a5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "be205e2a-3fd9-46d4-b067-f47bdb42803b",
   "metadata": {},
   "source": [
    "#### 3. Run Segmentation for the video and Please specify the arguments: "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ca9ad7e0-40d4-4b41-b54c-3e62a975945c",
   "metadata": {},
   "source": [
    "'load_path': the folder to load the original h5 file \\\n",
    "'save_folder: the folder to save segmentation file  \\\n",
    "'ch: the channel index used for tracking \\\n",
    "'zoom_factor': for low resolution zoom_factor = 2, staticfluild use zoom_factor = 1 \\\n",
    "'start_idx': the starting time index \\\n",
    "'end_idx': the ending time index \\"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "65481e77-372d-44c1-a746-cced8df3788a",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Physical devices cannot be modified after being initialized\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "\n",
    "gpus = tf.config.experimental.list_physical_devices('GPU')\n",
    "if gpus:\n",
    "    try:\n",
    "        for gpu in gpus:\n",
    "            tf.config.experimental.set_memory_growth(gpu, True)\n",
    "    except RuntimeError as e:\n",
    "        print(e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "4c30c363-b2ee-43d1-a766-a9cd401159e7",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "load_folder = '/work/venkatachalamlab/Hang/GNN_matching_git/dataset/ZM9624/'\n",
    "save_folder = 'seg'\n",
    "if not os.path.exists(save_folder):\n",
    "    os.makedirs(save_folder)\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "64a8eeef-7bb8-4fa3-bb69-de870e995b9e",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|          | 0/2 [00:00<?, ?it/s]2024-03-27 13:59:35.517074: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.517838: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.518539: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.519258: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.519963: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.520667: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.521363: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.522106: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.522827: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.523532: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.524233: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.524928: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.525783: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 13:59:35.525799: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 13:59:35.525879: W tensorflow/core/kernels/conv_ops_gpu.cc:144] None of the algorithms provided by cuDNN frontend heuristics worked; trying fallback algorithms.  Conv: batch: 1\n",
      "in_depths: 1\n",
      "out_depths: 32\n",
      "in: 1024\n",
      "in: 1024\n",
      "data_format: 1\n",
      "filter: 3\n",
      "filter: 3\n",
      "filter: 1\n",
      "dilation: 1\n",
      "dilation: 1\n",
      "stride: 1\n",
      "stride: 1\n",
      "padding: 1\n",
      "padding: 1\n",
      "dtype: DT_FLOAT\n",
      "group_count: 1\n",
      "device_identifier: \"sm_6.0 with 12786073600B RAM, 56 cores, 1328500KHz clock, 715000KHz mem clock, 3145728B L2$\"\n",
      "fusion {\n",
      "  activation_mode: kRelu\n",
      "  conv_scale: 1\n",
      "}\n",
      "version: 3\n",
      "\n",
      "2024-03-27 13:59:35.526940: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.527671: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 13:59:35.528466: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 13:59:35.528480: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 13:59:35.528886: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at conv_ops_fused_impl.h:625 : NOT_FOUND: No algorithm worked!  Error messages:\n",
      "  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n",
      "  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n",
      "  0%|          | 0/2 [00:00<?, ?it/s]\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 5\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m# for t_idx in tqdm(range(img_shape[0])):\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m t_idx \u001b[38;5;129;01min\u001b[39;00m tqdm(\u001b[38;5;28mrange\u001b[39m(\u001b[38;5;241m2\u001b[39m)):\n\u001b[0;32m----> 5\u001b[0m     label_z \u001b[38;5;241m=\u001b[39m \u001b[43mget_frame_segmentation\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m,\u001b[49m\u001b[43mmodel_2D\u001b[49m\u001b[43m,\u001b[49m\u001b[43mt_idx\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mzoom_factor\u001b[49m\u001b[43m,\u001b[49m\u001b[43mload_folder\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      6\u001b[0m     \u001b[38;5;66;03m# label[t_idx,0] = label_z\u001b[39;00m\n\u001b[1;32m      7\u001b[0m     save_var_h5(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mseg/\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;241m+\u001b[39m\u001b[38;5;28mstr\u001b[39m(t_idx)\u001b[38;5;241m+\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m.h5\u001b[39m\u001b[38;5;124m'\u001b[39m,[label_z],[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mlabel\u001b[39m\u001b[38;5;124m'\u001b[39m])\n",
      "File \u001b[0;32m/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py:119\u001b[0m, in \u001b[0;36mget_frame_segmentation\u001b[0;34m(model, model_2D, t_idx, ch, zoom_factor, folder_path)\u001b[0m\n\u001b[1;32m    117\u001b[0m img_zoom \u001b[38;5;241m=\u001b[39m scipy\u001b[38;5;241m.\u001b[39mndimage\u001b[38;5;241m.\u001b[39mzoom(img_original[\u001b[38;5;241m0\u001b[39m,ch],[\u001b[38;5;241m1\u001b[39m,zoom_factor,zoom_factor],order \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m)\n\u001b[1;32m    118\u001b[0m img_norm \u001b[38;5;241m=\u001b[39m normalize(img_zoom, \u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m99.8\u001b[39m)\n\u001b[0;32m--> 119\u001b[0m img_proj_pred \u001b[38;5;241m=\u001b[39m \u001b[43mget_mask_from_proj_pred\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel_2D\u001b[49m\u001b[43m,\u001b[49m\u001b[43mimg_zoom\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    120\u001b[0m pred, _ \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mpredict_instances(img_norm\u001b[38;5;241m*\u001b[39m((img_proj_pred\u001b[38;5;241m>\u001b[39m\u001b[38;5;241m0\u001b[39m)), n_tiles\u001b[38;5;241m=\u001b[39mmodel\u001b[38;5;241m.\u001b[39m_guess_n_tiles(img_norm), show_tile_progress\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m)\n\u001b[1;32m    121\u001b[0m label_z \u001b[38;5;241m=\u001b[39m scipy\u001b[38;5;241m.\u001b[39mndimage\u001b[38;5;241m.\u001b[39mzoom(pred,[\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m1\u001b[39m\u001b[38;5;241m/\u001b[39mzoom_factor,\u001b[38;5;241m1\u001b[39m\u001b[38;5;241m/\u001b[39mzoom_factor],order \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m)\n",
      "File \u001b[0;32m/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py:111\u001b[0m, in \u001b[0;36mget_mask_from_proj_pred\u001b[0;34m(model_2D, img_zoom)\u001b[0m\n\u001b[1;32m    109\u001b[0m img_proj \u001b[38;5;241m=\u001b[39m  np\u001b[38;5;241m.\u001b[39mmax(img_zoom,axis \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m)\n\u001b[1;32m    110\u001b[0m img_proj_norm \u001b[38;5;241m=\u001b[39m normalize(img_proj)\n\u001b[0;32m--> 111\u001b[0m img_proj_pred,_ \u001b[38;5;241m=\u001b[39m \u001b[43mmodel_2D\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mimg_proj_norm\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    112\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m img_proj_pred\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:777\u001b[0m, in \u001b[0;36mStarDistBase.predict_instances\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    764\u001b[0m \u001b[38;5;129m@functools\u001b[39m\u001b[38;5;241m.\u001b[39mwraps(_predict_instances_generator)\n\u001b[1;32m    765\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_instances\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    766\u001b[0m     \u001b[38;5;66;03m# the reason why the actual computation happens as a generator function\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    774\u001b[0m \n\u001b[1;32m    775\u001b[0m     \u001b[38;5;66;03m# return last \"yield\"ed value of generator\u001b[39;00m\n\u001b[1;32m    776\u001b[0m     r \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m--> 777\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_instances_generator(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    778\u001b[0m         \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[1;32m    779\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m r\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:729\u001b[0m, in \u001b[0;36mStarDistBase._predict_instances_generator\u001b[0;34m(self, img, axes, normalizer, sparse, prob_thresh, nms_thresh, scale, n_tiles, show_tile_progress, verbose, return_labels, predict_kwargs, nms_kwargs, overlap_label, return_predict)\u001b[0m\n\u001b[1;32m    727\u001b[0m res \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    728\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m sparse:\n\u001b[0;32m--> 729\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m res \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_sparse_generator(img, axes\u001b[38;5;241m=\u001b[39maxes, normalizer\u001b[38;5;241m=\u001b[39mnormalizer, n_tiles\u001b[38;5;241m=\u001b[39mn_tiles,\n\u001b[1;32m    730\u001b[0m                                               prob_thresh\u001b[38;5;241m=\u001b[39mprob_thresh, show_tile_progress\u001b[38;5;241m=\u001b[39mshow_tile_progress, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mpredict_kwargs):\n\u001b[1;32m    731\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m res \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    732\u001b[0m             \u001b[38;5;28;01myield\u001b[39;00m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtile\u001b[39m\u001b[38;5;124m'\u001b[39m  \u001b[38;5;66;03m# yield 'tile' each time a tile has been processed\u001b[39;00m\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:592\u001b[0m, in \u001b[0;36mStarDistBase._predict_sparse_generator\u001b[0;34m(self, img, prob_thresh, axes, normalizer, n_tiles, show_tile_progress, b, **predict_kwargs)\u001b[0m\n\u001b[1;32m    588\u001b[0m         \u001b[38;5;28;01myield\u001b[39;00m  \u001b[38;5;66;03m# yield None after each processed tile\u001b[39;00m\n\u001b[1;32m    590\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    591\u001b[0m     \u001b[38;5;66;03m# predict_direct -> prob, dist, [prob_class if multi_class]\u001b[39;00m\n\u001b[0;32m--> 592\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[43mpredict_direct\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    593\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m results[:\u001b[38;5;241m2\u001b[39m]\n\u001b[1;32m    594\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m _prep(prob, dist)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:398\u001b[0m, in \u001b[0;36mStarDistBase._predict_setup.<locals>.predict_direct\u001b[0;34m(x)\u001b[0m\n\u001b[1;32m    397\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_direct\u001b[39m(x):\n\u001b[0;32m--> 398\u001b[0m     ys \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeras_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m[\u001b[49m\u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnewaxis\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mpredict_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    399\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mtuple\u001b[39m(y[\u001b[38;5;241m0\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m y \u001b[38;5;129;01min\u001b[39;00m ys)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]"
     ]
    }
   ],
   "source": [
    "img_shape = get_img_shape(load_folder)\n",
    "[ch, zoom_factor] = [1,2]\n",
    "# for t_idx in tqdm(range(img_shape[0])):\n",
    "# for t_idx in tqdm(range(2)):\n",
    "#     label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n",
    "#     # label[t_idx,0] = label_z\n",
    "#     save_var_h5('seg/'+str(t_idx)+'.h5',[label_z],['label'])\n",
    "# print(\"finish the segmentation of movie in the folder path: \", save_folder)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "c8506d72-7424-4d9e-b2cc-8d68d17262d6",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "folder_path = load_folder\n",
    "t_idx = 0\n",
    "img_original,mask = get_volume_at_frame(folder_path+'data.h5',t_idx)\n",
    "img_zoom = scipy.ndimage.zoom(img_original[0,ch],[1,zoom_factor,zoom_factor],order = 0)\n",
    "img_norm = normalize(img_zoom, 1,99.8)\n",
    "img_proj =  np.max(img_zoom,axis = 0)\n",
    "img_proj_norm = normalize(img_proj)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "9fc1c47c-dfd6-440f-b5f6-166fc648389f",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "d88757b7-9348-41ca-bd10-2a1602f6daf0",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-27 14:11:08.392995: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.394011: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.394996: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.395957: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.396913: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.397870: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.398827: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.399841: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.400816: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.401761: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.402690: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.403586: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.404657: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 14:11:08.404675: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 14:11:08.404758: W tensorflow/core/kernels/conv_ops_gpu.cc:144] None of the algorithms provided by cuDNN frontend heuristics worked; trying fallback algorithms.  Conv: batch: 1\n",
      "in_depths: 1\n",
      "out_depths: 32\n",
      "in: 1024\n",
      "in: 1024\n",
      "data_format: 1\n",
      "filter: 3\n",
      "filter: 3\n",
      "filter: 1\n",
      "dilation: 1\n",
      "dilation: 1\n",
      "stride: 1\n",
      "stride: 1\n",
      "padding: 1\n",
      "padding: 1\n",
      "dtype: DT_FLOAT\n",
      "group_count: 1\n",
      "device_identifier: \"sm_6.0 with 12786073600B RAM, 56 cores, 1328500KHz clock, 715000KHz mem clock, 3145728B L2$\"\n",
      "fusion {\n",
      "  activation_mode: kRelu\n",
      "  conv_scale: 1\n",
      "}\n",
      "version: 3\n",
      "\n",
      "2024-03-27 14:11:08.406081: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.407002: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:08.408054: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 14:11:08.408073: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 14:11:08.408585: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at conv_ops_fused_impl.h:625 : NOT_FOUND: No algorithm worked!  Error messages:\n",
      "  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n",
      "  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m img_proj_pred,_ \u001b[38;5;241m=\u001b[39m \u001b[43mmodel_2D\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mimg_proj_norm\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:777\u001b[0m, in \u001b[0;36mStarDistBase.predict_instances\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    764\u001b[0m \u001b[38;5;129m@functools\u001b[39m\u001b[38;5;241m.\u001b[39mwraps(_predict_instances_generator)\n\u001b[1;32m    765\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_instances\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    766\u001b[0m     \u001b[38;5;66;03m# the reason why the actual computation happens as a generator function\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    774\u001b[0m \n\u001b[1;32m    775\u001b[0m     \u001b[38;5;66;03m# return last \"yield\"ed value of generator\u001b[39;00m\n\u001b[1;32m    776\u001b[0m     r \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m--> 777\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_instances_generator(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    778\u001b[0m         \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[1;32m    779\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m r\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:729\u001b[0m, in \u001b[0;36mStarDistBase._predict_instances_generator\u001b[0;34m(self, img, axes, normalizer, sparse, prob_thresh, nms_thresh, scale, n_tiles, show_tile_progress, verbose, return_labels, predict_kwargs, nms_kwargs, overlap_label, return_predict)\u001b[0m\n\u001b[1;32m    727\u001b[0m res \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    728\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m sparse:\n\u001b[0;32m--> 729\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m res \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_sparse_generator(img, axes\u001b[38;5;241m=\u001b[39maxes, normalizer\u001b[38;5;241m=\u001b[39mnormalizer, n_tiles\u001b[38;5;241m=\u001b[39mn_tiles,\n\u001b[1;32m    730\u001b[0m                                               prob_thresh\u001b[38;5;241m=\u001b[39mprob_thresh, show_tile_progress\u001b[38;5;241m=\u001b[39mshow_tile_progress, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mpredict_kwargs):\n\u001b[1;32m    731\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m res \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    732\u001b[0m             \u001b[38;5;28;01myield\u001b[39;00m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtile\u001b[39m\u001b[38;5;124m'\u001b[39m  \u001b[38;5;66;03m# yield 'tile' each time a tile has been processed\u001b[39;00m\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:592\u001b[0m, in \u001b[0;36mStarDistBase._predict_sparse_generator\u001b[0;34m(self, img, prob_thresh, axes, normalizer, n_tiles, show_tile_progress, b, **predict_kwargs)\u001b[0m\n\u001b[1;32m    588\u001b[0m         \u001b[38;5;28;01myield\u001b[39;00m  \u001b[38;5;66;03m# yield None after each processed tile\u001b[39;00m\n\u001b[1;32m    590\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    591\u001b[0m     \u001b[38;5;66;03m# predict_direct -> prob, dist, [prob_class if multi_class]\u001b[39;00m\n\u001b[0;32m--> 592\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[43mpredict_direct\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    593\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m results[:\u001b[38;5;241m2\u001b[39m]\n\u001b[1;32m    594\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m _prep(prob, dist)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:398\u001b[0m, in \u001b[0;36mStarDistBase._predict_setup.<locals>.predict_direct\u001b[0;34m(x)\u001b[0m\n\u001b[1;32m    397\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_direct\u001b[39m(x):\n\u001b[0;32m--> 398\u001b[0m     ys \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeras_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m[\u001b[49m\u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnewaxis\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mpredict_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    399\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mtuple\u001b[39m(y[\u001b[38;5;241m0\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m y \u001b[38;5;129;01min\u001b[39;00m ys)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]"
     ]
    }
   ],
   "source": [
    "img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "072de84f-1990-4349-a2a4-80d1ff1fdbaa",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "46e96b2d-3525-447b-b6cc-e63d32909e05",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-27 14:11:30.703046: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.704408: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.705502: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.706582: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.707671: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.708705: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.709706: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.710749: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.711759: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.712763: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.713758: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.714748: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.716316: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 14:11:30.716339: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 14:11:30.716428: W tensorflow/core/kernels/conv_ops_gpu.cc:144] None of the algorithms provided by cuDNN frontend heuristics worked; trying fallback algorithms.  Conv: batch: 1\n",
      "in_depths: 1\n",
      "out_depths: 32\n",
      "in: 1024\n",
      "in: 1024\n",
      "data_format: 1\n",
      "filter: 3\n",
      "filter: 3\n",
      "filter: 1\n",
      "dilation: 1\n",
      "dilation: 1\n",
      "stride: 1\n",
      "stride: 1\n",
      "padding: 1\n",
      "padding: 1\n",
      "dtype: DT_FLOAT\n",
      "group_count: 1\n",
      "device_identifier: \"sm_6.0 with 12786073600B RAM, 56 cores, 1328500KHz clock, 715000KHz mem clock, 3145728B L2$\"\n",
      "fusion {\n",
      "  activation_mode: kRelu\n",
      "  conv_scale: 1\n",
      "}\n",
      "version: 3\n",
      "\n",
      "2024-03-27 14:11:30.717892: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.718877: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:11:30.719969: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 14:11:30.719988: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 14:11:30.720527: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at conv_ops_fused_impl.h:625 : NOT_FOUND: No algorithm worked!  Error messages:\n",
      "  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n",
      "  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[25], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mmodel_2D\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mimg_norm\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:777\u001b[0m, in \u001b[0;36mStarDistBase.predict_instances\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    764\u001b[0m \u001b[38;5;129m@functools\u001b[39m\u001b[38;5;241m.\u001b[39mwraps(_predict_instances_generator)\n\u001b[1;32m    765\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_instances\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    766\u001b[0m     \u001b[38;5;66;03m# the reason why the actual computation happens as a generator function\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    774\u001b[0m \n\u001b[1;32m    775\u001b[0m     \u001b[38;5;66;03m# return last \"yield\"ed value of generator\u001b[39;00m\n\u001b[1;32m    776\u001b[0m     r \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m--> 777\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_instances_generator(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    778\u001b[0m         \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[1;32m    779\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m r\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:729\u001b[0m, in \u001b[0;36mStarDistBase._predict_instances_generator\u001b[0;34m(self, img, axes, normalizer, sparse, prob_thresh, nms_thresh, scale, n_tiles, show_tile_progress, verbose, return_labels, predict_kwargs, nms_kwargs, overlap_label, return_predict)\u001b[0m\n\u001b[1;32m    727\u001b[0m res \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    728\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m sparse:\n\u001b[0;32m--> 729\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m res \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_sparse_generator(img, axes\u001b[38;5;241m=\u001b[39maxes, normalizer\u001b[38;5;241m=\u001b[39mnormalizer, n_tiles\u001b[38;5;241m=\u001b[39mn_tiles,\n\u001b[1;32m    730\u001b[0m                                               prob_thresh\u001b[38;5;241m=\u001b[39mprob_thresh, show_tile_progress\u001b[38;5;241m=\u001b[39mshow_tile_progress, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mpredict_kwargs):\n\u001b[1;32m    731\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m res \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    732\u001b[0m             \u001b[38;5;28;01myield\u001b[39;00m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtile\u001b[39m\u001b[38;5;124m'\u001b[39m  \u001b[38;5;66;03m# yield 'tile' each time a tile has been processed\u001b[39;00m\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:592\u001b[0m, in \u001b[0;36mStarDistBase._predict_sparse_generator\u001b[0;34m(self, img, prob_thresh, axes, normalizer, n_tiles, show_tile_progress, b, **predict_kwargs)\u001b[0m\n\u001b[1;32m    588\u001b[0m         \u001b[38;5;28;01myield\u001b[39;00m  \u001b[38;5;66;03m# yield None after each processed tile\u001b[39;00m\n\u001b[1;32m    590\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    591\u001b[0m     \u001b[38;5;66;03m# predict_direct -> prob, dist, [prob_class if multi_class]\u001b[39;00m\n\u001b[0;32m--> 592\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[43mpredict_direct\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    593\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m results[:\u001b[38;5;241m2\u001b[39m]\n\u001b[1;32m    594\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m _prep(prob, dist)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:398\u001b[0m, in \u001b[0;36mStarDistBase._predict_setup.<locals>.predict_direct\u001b[0;34m(x)\u001b[0m\n\u001b[1;32m    397\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_direct\u001b[39m(x):\n\u001b[0;32m--> 398\u001b[0m     ys \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeras_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m[\u001b[49m\u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnewaxis\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mpredict_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    399\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mtuple\u001b[39m(y[\u001b[38;5;241m0\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m y \u001b[38;5;129;01min\u001b[39;00m ys)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]"
     ]
    }
   ],
   "source": [
    "model_2D.predict_instances(img_norm[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b545883-daab-4c51-9599-3575d1685247",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e4bcca57-9704-4fc5-a4e9-d9d65ca2ae92",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72a4513a-8430-430c-9aee-01917e1e53bb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "2e6d3540-f200-492e-ae55-d79347fd58eb",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAbsAAAGiCAYAAAB+sGhNAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/H5lhTAAAACXBIWXMAAA9hAAAPYQGoP6dpAABNxklEQVR4nO3de3Rc5X3v//e+zE0aaWRJlmThC07CzYEQghPHgeY0xQsnoWk4oT2HHjeHpqxwmtppCLnBSaEnTYgpPSunJU2gyeoJrF8gafP7hVw4Ca2PSaAkjgFzCRhinEKwwUiyLWukGc1t7/38/tgz25KR7yNL2vq81tLCmtnas2djzcfP5fs8ljHGICIiEmP2TF+AiIjIdFPYiYhI7CnsREQk9hR2IiISewo7ERGJPYWdiIjEnsJORERiT2EnIiKxp7ATEZHYU9iJiEjszeqw+8pXvsLpp59OOp1m1apVPPLIIzN9SSIiMgfN2rD7p3/6J6677jr+8i//kscff5zzzz+ftWvXMjQ0NNOXJiIic4w1WxeCXrVqFW9961v5+7//ewCCIGDJkiV89KMf5frrr5/hqxMRkbnEnekLmEq1WmXbtm3ccMMN0WO2bbNmzRq2bNky5c9UKhUqlUr0fRAEDA8P09XVhWVZ037NIiLSPMYYxsbG6O/vx7ZPvhNyVobdvn378H2f3t7eSY/39vbyq1/9asqf2bhxI5/73OdOxeWJiMgpsnv3bhYvXnzS55mVYXcibrjhBq677rro+3w+z9KlS7mY9+KSmMErExGR4+VR42F+RFtbW1PONyvDrru7G8dxGBwcnPT44OAgfX19U/5MKpUilUq95nGXBK6lsBMRmVPqs0maNQw1K2djJpNJLrzwQjZv3hw9FgQBmzdvZvXq1TN4ZSIiMhfNypYdwHXXXcdVV13FypUredvb3sbf/u3fUiwW+dCHPjTTlyYiInPMrA27//yf/zN79+7lpptuYmBggDe/+c3cf//9r5m0IiIicjSzts7uZI2OjpLL5fht3q8xOxGROcYzNX7K98nn87S3t5/0+WblmJ2IiEgzKexERCT2FHYiIhJ7CjsREYk9hZ2IiMSewk5ERGJPYSciIrGnsBMRkdhT2ImISOwp7EREJPYUdiIiEnsKOxERiT2FnYiIxJ7CTkREYk9hJyIisaewExGR2FPYiYhI7CnsREQk9hR2IiISewo7ERGJPYWdiIjEnsJORERiT2EnIiKxp7ATEZHYU9iJiEjsKexERCT2FHYiIhJ7CjsREYk9hZ2IiMSewk5ERGJPYSciIrGnsBMRkdhT2ImISOwp7EREJPYUdiIiEnsKOxERiT2FnYiIxJ7CTkREYk9hJyIisaewExGR2FPYiYhI7CnsREQk9hR2IiISewo7ERGJPYWdiIjEnsJORERiT2EnIiKxp7ATEZHYU9iJiEjsKexERCT2FHYiIhJ7CjsREYk9hZ2IiMSewk5ERGJPYSciIrGnsBMRkdhT2ImISOwp7EREJPYUdiIiEnsKOxERiT2FnYiIxF7Tw27jxo289a1vpa2tjZ6eHi6//HJ27Ngx6Zhyucz69evp6uoim81yxRVXMDg4OOmYXbt2cdlll9HS0kJPTw+f+tSn8Dyv2ZcrIiLzQNPD7sEHH2T9+vX84he/YNOmTdRqNS699FKKxWJ0zMc//nF++MMf8p3vfIcHH3yQPXv28IEPfCB63vd9LrvsMqrVKj//+c+56667uPPOO7npppuafbkiIjIPWMYYM50vsHfvXnp6enjwwQd55zvfST6fZ+HChdxzzz38/u//PgC/+tWvOOecc9iyZQtvf/vb+fGPf8zv/u7vsmfPHnp7ewG44447+MxnPsPevXtJJpNHfd3R0VFyuRy/zftxrcR0vkUREWkyz9T4Kd8nn8/T3t5+0ueb9jG7fD4PQGdnJwDbtm2jVquxZs2a6Jizzz6bpUuXsmXLFgC2bNnCeeedFwUdwNq1axkdHWX79u1Tvk6lUmF0dHTSl4iICExz2AVBwLXXXstFF13EueeeC8DAwADJZJKOjo5Jx/b29jIwMBAdMzHoGs83npvKxo0byeVy0deSJUua/G5ERGSumtawW79+Pc888wzf/va3p/NlALjhhhvI5/PR1+7du6f9NUVEZG5wp+vEGzZs4L777uOhhx5i8eLF0eN9fX1Uq1VGRkYmte4GBwfp6+uLjnnkkUcmna8xW7NxzKFSqRSpVKrJ70JEROKg6S07YwwbNmzg3nvv5YEHHmD58uWTnr/wwgtJJBJs3rw5emzHjh3s2rWL1atXA7B69WqefvpphoaGomM2bdpEe3s7K1asaPYli4hIzDW9Zbd+/Xruuecevv/979PW1haNseVyOTKZDLlcjquvvprrrruOzs5O2tvb+ehHP8rq1at5+9vfDsCll17KihUr+OAHP8itt97KwMAAf/EXf8H69evVehMRkePW9NIDy7KmfPwb3/gGf/zHfwyEReWf+MQn+Na3vkWlUmHt2rV89atfndRF+dJLL/GRj3yEn/70p7S2tnLVVVdxyy234LrHls8qPRARmbuaXXow7XV2M0VhJyIyd825OjsREZGZprATEZHYU9iJiEjsKexERCT2FHYiIhJ7CjsREYk9hZ2IiMSewk5ERGJPYSciIrGnsBMRkdhT2ImISOwp7EREJPYUdiIiEnsKOxERiT2FnYiIxJ7CTkREYk9hJyIisaewExGR2FPYiYhI7CnsREQk9hR2IiISewo7ERGJPYWdiIjEnsJORERiT2EnIiKxp7ATEZHYU9iJiEjsKexERCT2FHYiIhJ7CjsREYk9hZ2IiMSewk5ERGJPYSciIrGnsBMRkdhT2ImISOwp7EREJPYUdiIiEnsKOxERiT2FnYiIxJ7CTkREYk9hJyIisaewExGR2FPYiYhI7CnsREQk9hR2IiISewo7ERGJPYWdiIjEnsJORERiT2EnIiKxp7ATEZHYU9iJiEjsKexERCT2FHYiIhJ7CjsREYk9hZ2IiMSewk5ERGJPYSciIrGnsBMRkdhT2ImISOwp7EREJPYUdiIiEnvTHna33HILlmVx7bXXRo+Vy2XWr19PV1cX2WyWK664gsHBwUk/t2vXLi677DJaWlro6enhU5/6FJ7nTffliohIDE1r2D366KP8wz/8A29605smPf7xj3+cH/7wh3znO9/hwQcfZM+ePXzgAx+Invd9n8suu4xqtcrPf/5z7rrrLu68805uuumm6bxcERGJqWkLu0KhwLp16/j617/OggULosfz+Tz/+I//yJe+9CV+53d+hwsvvJBvfOMb/PznP+cXv/gFAP/6r//Ks88+yze/+U3e/OY38573vIfPf/7zfOUrX6FarU7XJYuISExNW9itX7+eyy67jDVr1kx6fNu2bdRqtUmPn3322SxdupQtW7YAsGXLFs477zx6e3ujY9auXcvo6Cjbt2+f8vUqlQqjo6OTvkRERADc6Tjpt7/9bR5//HEeffTR1zw3MDBAMpmko6Nj0uO9vb0MDAxEx0wMusbzjeemsnHjRj73uc814epFRCRumt6y2717Nx/72Me4++67SafTzT79Yd1www3k8/noa/fu3afstUVEZHZretht27aNoaEh3vKWt+C6Lq7r8uCDD3Lbbbfhui69vb1Uq1VGRkYm/dzg4CB9fX0A9PX1vWZ2ZuP7xjGHSqVStLe3T/oSERGBaQi7Sy65hKeffponn3wy+lq5ciXr1q2L/pxIJNi8eXP0Mzt27GDXrl2sXr0agNWrV/P0008zNDQUHbNp0yba29tZsWJFsy9ZRERiruljdm1tbZx77rmTHmttbaWrqyt6/Oqrr+a6666js7OT9vZ2PvrRj7J69Wre/va3A3DppZeyYsUKPvjBD3LrrbcyMDDAX/zFX7B+/XpSqVSzL1lERGJuWiaoHM3/+l//C9u2ueKKK6hUKqxdu5avfvWr0fOO43DffffxkY98hNWrV9Pa2spVV13FX/3VX83E5YqIyBxnGWPMTF/EdBgdHSWXy/HbvB/XSsz05Yg0j+1M/j7wp+c1puO8IsfIMzV+yvfJ5/NNmYMxIy07ETkBtoPzuqWMXNjL8BstAHI7ofO7v8R4HnYmDd2dWJ6PKRTx9+0/6vmiQKsHqJVwsdyDHwvG8zA1T8Enc57CTmSOcNqzvHLZIqoXj7Gid4A9hRx727vp/kkHeB7VM/oZPieN5UPuN1Xcn4xMHVITW4YT/mwlXOy2LFY6TdDVjuUFWJUqwe49mBoKPJnTFHYis8FRug2tVIrg9YsZPb/KmqUvsDA5BsDQgnZwHSpn9DJ8dopyV9jiq2VTnPZUB/7wyKTzWvUJXnYmrIE1NS9qvVmuC10LGD+9gz3vDLv+W161WHQ/mFeHCEplBZ7MWQo7kVnAzqSxMmmsbCsmlQTA3/liGC62g51JM97bglW0eXr/InKpBewbbyH1QhqvJ8foshSVDgs/YzAO+BnwzlyMva2AqYTnsBIuzqJeqku62HdmmkpnGIxLfrQf85uXsduyPLehi7e9ZSdvcCu0uyUqQYKfcSELH2/HeerXr+3W1NiezBEKO5GZZjtYmTR0LWDX7/VQazM4JYtlt+/FH8lHh6X2lWnd1cZwcSF7F5exBlMsfrSG5Qe4JYMVWPhpg12zsKsWdqUeTBN4PTlGT08zegYEiQDLtyi+Lkc2XwDXwemq0J0s0pUskLI89tdaqbbB/nNb6H3WxV7QAZ6Hf2BEY3kypyjsRGaYlXCht5vBizrJXTLAqoW/4fHhJVj/TxbqYReUyjgv7KGn7XS8Fgc/lSQx5pHZ9iLBsj6cqsEpg1O2cAsWtgfO/jE8ODj5xHUpntZCYbFFrd3D8i3sKlTbbHAdTCpJe9s4ALXAoRCkqAQJSv0+xnHwz1yKccN1KBIvQDBWwNT3mFTwyWynsBM51epdipbrYrxwrOzXH+zk9j/4Gn1OgZ+On8nPaq8jtbe+6HngYyo+fqVC4uECCTjYYmvPUutI41QCFuwMcJ4JAEjuGye/chHOeX20PLCdoFTGeB6jSx38jCEx6mBscMqQHPOp9S/ArngUn2jnX89MYwKbIAi7Od2FJcpkKPdmALB8g9PbiZVrw/J9LM8Hz8fbM6DAk1lLYSdyMurBFYXP0T7s68fbbVmsbCt4PqZcpvNNewEY8LNs3nc2oz/vIVd78TU/biqVyedKp/FTNn7KxvYMqZeGASi9votin0Myb2hNuFheGK7tu3wKvkO1DawAUgcMpS6HwE3TuqvAaQ9WGR7KUnjHOLZtsOyAttYyw2Mp3PEAP2Vj+fXSXNcB38e4DhbU78Mx3AORGaCwEzlBTndXOINxYl1auXywvq0ebHCwm68xScTvaiNIhc+5+TIjj3Vya+o9PL+zn6X/B5Y98BTBsYSG6+KWfNySj+UZcBxqPW2MLktgVw3JQoCVzWIDVkeO1l0FWl6xGTkri5eBIGlh+QYvY+G3JLECQ/dTJYqLM9Q6fAig8O+tdL0A7lgBp2RjeWHrEc8HZ0Lgue5rxghFZguFnciJ8rxJQQdMKsh22rNY2SwA/t59mNrB5y0vwLSE419+a5LFP6kwNLSUpS95tG75d/xi8ZguwRQKJIbDmjgqVQDc0TIte5MYB1IjNWiUFjR+xrWxfYNTtYCwleZUDXbFo9qSgiR0/dJQ7HMxDmRfCWj/dRG74hHg4rUlsVoTJPfUwPfr78cnlksxSWwo7EROUFAqhy2mCfs2NiZsQNiSCnKtYbiUywRjhbCl5/lY5RqmMxO2xoDk0y/R/5yLf2AE/1hbR4GPP1rAeWUoCjR7QQemNU1msIxxbJzx6qRrKve24KdskmMBtRabwLFIFgypAx5BysX2DIFrkdsxRvuvbfzWBInhUlhgXixRuGAR+9/oECQNndu76XjmAFa+AJ4XvrdS/YUaxerq0pRZQmEncoJMpRIG02gBO5M+uGRX4/lUEuPaYYh0LcDu7ca4Nn7Kxbg27mgFZ//YsS3tdTiBP6nbtPa2XiodYUF4+6MvY+oh6yzqpfz6hYwtdvEyFk7V0DoQ0PlcCXdoFFJJap0tADjVsJvSGS7g5MNu0WpHgn3ndtH2W0Ncvuh5AP7fM99MaWEXPY+EdYHuUB6HsMu2MY455wrRVTcYWwo7kZNR/2AMSmUA/Fohesoqlg5uGOk6BGk3bCH5YZjYZQ8zkscfLdAMTnuW8Y4EXsbCLRlMayacOFK/NgjH6ACMY4WhV6zCvmGsjhx2axLjJrA8E15nOewW9Vo68FMWtfML/M6i57mw9TfsKC/izL69vNCRZfy0MCRbACeVxK5UMYVi+NqeGxa1z0aHWRt01l6vnBSFnUgzTNEaCA6MYHseTqVKkGvFLntQqWLXQ8SUy2HXYyZ98i0g2wHXJTnqkRoxeBmH4pmdpAdLOOkkeD7JfeNYfhKcMPBaX61i54swobvV2Ba49THFchnLdRlbnMDPWHh7M7ywpJs3trzCstQ+9re1sn3ZYkYqCSwfjNNCyx4bu5LCLoRjjrNyworthOOp9e5nUy7jjxYmLYI9adarxILCTuQQdmsrwMkFkO1gt2Ux2RZwHKxyfTLHyCjU6+vwPOy2bPQjk17vWLvTbAensyP6NjVQoNYZjss5lSDsRs21YJc97HyR1oF2vIxFy2CN5O4DUK6E10gYcNX2cNzOKSZx69dp++ADLS87bOtaSptb4ZzWV3mx2EXrr8OgA3AqhiDlUGtLkCksgP0HDpYjwKzpHmzMkI0mFx0yyWhWBrScNIWdCExa/d9e2AWANZKftFzX8bASLqRTUF/nkko17BZsfLAeMpPTyqSxPA9ww3E/1w1XKDnSyiT1FgodE/b68nyCZFhzlxjzCFIH35dThLZn92PSibBFV65ErTfTmsZrC681cK1wpZR0CstzcaoGzwcrsMg81sIDQ+fxf9NvpOUll/bdAZVcuBJL4FqMLU5hHPBaumjdlcJ+aSB6vyd6L6dDNKnIDWsVCfxZF8rSXAo7kTor4RJceDYv/k4rlg/Zl09jwT8/juW64XOl8pG7txqLLS/sBoi6BgGs37yMgbC1Vy4TlMKQIZMOP2zrMyYbCzWXesPgaX96/8EFoQ8V+OFkEGfCNj35MdLFEiadpPT6rjD4kjauY2MXkrD/ALbrRtcAhDNKcwdbmOFC0i5uvVh8wSODBLkWSv2tJAoeqe/uw7RmqPa0YmyL5JhDerDE6BtaSZTC8Ug/aVFcmqXF6cfyg3AM8Gj3r34PDxc2VirVlGXJTKVCMFaI/l+YxphmfaUaiSeFncwPx9At6CzsZvjMFirdAZYPyTE73I2gI4dpzeDsH8Eb2vfa80xY/ste2EV1SRd2xcOuhAHWKMI2XridDm54bFS64LqYUjh+F+RaKSxJUclZ+EmL9P52nB2Hv+6gVMathxv10AsOjGAv6CBIRtNjsPwAk07AaT1Y+SKmtxPbC8LC8P0HwPNxSh60uzgVgztWxSqMh9fq+TiFcVrz41E3LKkkieESfmsSuxpOukmOBQRufQJMMgxNIJyNSrgs2lHD7gitWDuThgzhhJ6TDLygVD44Y/QYaxplblPYyfxwlA9HK+ESdLVTWmhhFlQIqg7VNhsrHW6hY1wbt9KCU86+pjvOSoRdj1Y2S3VJF8X+FE41SWqkRnKoCJUq/oQZkY1WnJ1Jh2N2jTE8wGtP4yfrMyWr4CdtHI4g8DGtGbyuViwvwHEdGCsQHBjBHe8jcC3ccR8/4+JnXOxqQHVpG/vOdQmSkByB0/6Pj1Wp4uYdkvVjnOFC2MU5oYYw2L0nfL+ui+26WMUSVjmDVamGK6j0tmBSFtWsjeVDatwPd17wbeyyR+Cd4FhYPeisdNi9a5XKJ78sWb1GUV2W84fCToSwexEvwC2Bkwjwqg5WQDR5A8DvzIbBc0jYmZoHpy+kvDhH/vQkfsYiUTD4ySTGtkgNhHV4VuLgOFxj2bCo6DydhH3D2I8/T/fwYkqL20iM1Ui8MIB3pFZpfazRKYYzPK18ARLhEmapbb8GoLTqDMpd4a/6+EKb6sVjLO08wIJ0uMPBs87ZnLb5AFa5Rvrf92IKRehop3be66h2JEiO1Ei+OBRdt5Vww10SCkXMgRH8Uhk7k6alvlRZ6oBN6uV8vcUYrtxiat5JzXCMxkDr/69MqXzyM1gVdPOKwk4EMKUyVqVKx84qhaUZ0kWLrmc9LM8PuwBd+/A/XP/QtKtB2BoLNwfA9g12NewqtBYvAtfBHtwXrqTiuphUkqBeYG6nkuGizqP7sH79G1ry3ZjWDCbbgj129NKEaLan64RLlLkOlMOxqSBpRzMmvRbw/bCrseo70WNee5pEsRytcZl/cw8jr3covqGGXUyRfXEZi+7YF/6joGsBta5W7Eobzv4x2Ls/DKPBvSQG9x68LfVxSSuTDpcqO4mCbVML/1/gHqyHi1ZrETkGCjuJv2P4kA1KZexXh8jsG+aMrYDr4g+P4AHOSDac1FEqT+6OnGhwL8lKla6hJH4uTDt3KE+Qa6XW0xaNnyXSLnahEq0p6QwXwtKE/Fi0nJi9pJ9aT3vU7ZhIJXEG9+EPj0z5PszLrwL1gujuToKutvBtF5JYuTaSIzXccTtcBuwFl1dfl6LYkaS3ZZQX8t30PF4juTPsojSeR3BaD0O/X+J9ZzzDO9p+zYCX4+9++S6c7/fi9eSodKcxjoXlJ0m0JHFeHQw3n60vWdYYA7NSqXD5snQS05rGeWUobNkebwsv8AmKxahkIJgwoUTkWCnsJP6O5UMx8MOWiOe+ZsbfsUyZ90cL2PX6LGd/Y1q7C7lWLD/AT7n1UoDwV85vSWJci+RQEWv/SNgCq3cHBrkW/IxL4FoEroMz7uJMGDuLTNhVAZg0M9M49UWmc5lwJ/Ox8NrSA0VKCxewJ9nB4HA75tU0Zz4/COlU2H1JuFB0W2uZ12X2cnZykJ+PvQFvbwYYCWdW1rf4cSpBNAmnMQ5pPG/SPy5MOkllWSeVBS7txXJ9vK0+cSfx2nt9KCuVit6bP5KfVCIicjwUdiINjVqrE2wxNGb4BcMjQH0CSn2cyU050QzNWmcGP2ljHAs37YaLRE/RTWkcC6cSRKuZTHW9UO8mnDDJJdqCx3XCVVEcO3ztsgeD++jdYmNX23Gq0P5SBRwH44RlBqZQxDg2B4azPNmzlD43zw92vIkFT9tht6pjkzxQwW9NYFd8nHwJv+YREF7foeFVW9TBeG+Cataipacd59UhIFzaDCDgCJNNGjMwAePWW4xqzckJUtiJTHSiH6aNlsyEOq2gWAw/oG2HZP3D3cpmcVIufjKFW/LDLk3A6ezAcsNdD+x/f5lUd2dYkO75MLj3sDMHrXoZA64bjosVS+D79XUpfRLFUrRBLAC93fgtSbqfLOAO5TGuE5UsGNchWNbH6BtaaXvc5pHHz+eJwptY9kKFSkfAyLkLSI14JMZqpHYOYgqF6LpMxX9Nd3Gju7KWCWeX+hmXxMIubM8PSyUApzAetWoPfX9W4uBegRaHZ6VS9QlGnmZYymEp7EQmavLWNFYqFdXUmZqHXfNwAbvSHk4qGdwbtoaW9RO4NrbnhQXP+4axstlo3cbDXU9Uu+fV69gKBSzqBeL1SSqkU+Gu6IDXmqTW5uIkbZx8MjymsboLEPS04yct/HS4k3mQpN4KDevmgqRNkHIwhcLBZbUmLqJ8SCvNHS2TzifD7YZKXnQ9jYClXrBPcYqxyAnLdh12CS/bwVnYjd/bgV2o4Ljuie8gIbGmsBOZ6BhCbuI40pGOdzpy0LuQIJvCGRwhODBCUCyG4bR3X7gkWKmM057FT4WbototS3HGqwSA/e8vH3W8sLHN0KQd0Scsamy3ZTGNJcv8sNvRqS8L1tiJwYaw9TeSxx1KkupNAzbJQkBmsBqGY8Xgjgf1cTofqyMHrhOWYuwbnrQM2sRwDp5+nvaXsrR3d2JeHQrfV/21gYOtw6lM3L7ocPe4s4Pq8h5e/p0MThkWPN9Fy70KO3kthZ3IsWrUtC3oCAvBJ3TjTcXUPOz8GE6lOml5rmi/t8akjpqH15ak1J0gs6+G5bvYFS8sITiWbrlDlrmyUqlofU3jeeHMT8cJu0UH95ECgmyqvqmsF3aVNuwbpu1pSC/qwK54OPkS0IZxLfykjRUYnGI1DFDXCX+2EXQd7eFqK0ye1OOPFqKJKY1aw8ZYZnCSy39Z2VaK/SmMYzhyZ6fMdwo7kSM5ZPafnUkT9HZiXBvHC1tRh9MIN6veNdk436RWWOCH0/3dcENVKwhnOgYpF4cT21/Nct0wKBs8H+PUg8nzCH6zG2dhWMeH64RhWK5EXa1WqUwCoq7GxNAYJp3ASbk4xSrW/hFMrg3j2lG8WNlWvM5s+LznHyy8b4xl1rs3o8WWy5VJ9+hE1foXUFpo45QgOWpoeWX8pM4n8aWwEzkKpz0L3Z3hh7jnU2tNEqQc7HIHTrl8+K7Gen0YE9debIxvNfZNq4Whl3l5DL81GbakfB/L8wkOjBx/TVpja6HWDCadiMYFJx2SSRMcGIGu9rCYfCicwNJYezIolaN1MXGdcBPYYhl3sB4krhtu3wPRIsrmtJ7wLadd7Epy8v3ryEF356R6Qm9oX7iKTGdHGMCHlCSE9+borb7EngP0eGEJhL1/FH/vPszx3TGZJxR2Ikczcb8zL9w2x/IMVKpH3vts0u7XlejPjS5GGh/wgY+1fwSn0oLl+eH0/3oAnIhG16Xlha22YEIXYmNHBtJJqp0ZalkXy28NZ23Wx9GcdDo8R64Nk06E3Z1QbxnWV2mZsHOCnUljeUG42HO5FgZlnZVKYWWz+LmWeklEW7iVUbEIhOOKBg4uEn2cdXRmJI9LWDLhHaboXgQUdiJHFYwVcOof7kA4QcMLYGT0iIHUaKFYrnuw1TJxD7uEGxaxV/xw9RTPgwnF4yfShUngY0pl7HQ6DJFyNQpUO5ONui6Na1PpSFDJ2bjjLm5rfY2z+rY+uC34uUxUpxekXBL5sCu2saRYg/E87HwBclmsYulgl23jvdfr8/yWJHa9e5b6xJOoNjDhnlDB+MTxQAWdHInCTuQoTM3DGxiMvrd+8Uw4U/BIP9QoiK6HQmNlzcbGsBC2ShrHGs8Lw65eQkA6jZPNRjM4j8fE+r5GADRaWNX60mWpgUJYStDIl8bsSNeG1ky4CWzKDUsNXAvbs0k0gqlQ36aoI4ebTuMNDOLtGYA9jQs4pF6uUsXy6xNSUi52OhG+VqWCmbBX4KTxvWN+s9qDTo6Nwk7i6SQWHZ7kMJumHpMJBd9AtKQWhK2j19SRZTh4bD187Lbsie+3dkiBtymXCZI2fsqm2tNKy54ykCZ/epL0gg5a9pQP7p5QLGFXMgTJJE41LDfAdfH37ov27Tvca016uFTGKhSxGws4ewF2vkjQuK4pumudzo7wuVI5PnvNNevvo5wwhZ3MXRO6vaxEWFPWWDbLry/ZddLnP8EPqEadG3Cw4LtRauA64dgc9b3hMmn8kXw4/uUe/DmTy0IqiVMuRyFoSuWD5znOySvBWIHUQIFqT2u4T16xRuqAx9hpKcK2Z5rcYweia3Ze2IPruphsS31yjhct3xUe40+9jNmkF63Xyg2PhC24mkcwxSor0X1LpQ7u3J6I0ceTgm7Gxehvk8wr9aBz+/uiVhD1ZaiscvXExrsOdRIfUKbmHRyPqgedqXnRMl6UK+FOAQ3192NK5YMf8rlsONEkm42W17KzreH7LBTwG0FxDKFst7aGszQ9H3e0gt1YkDpl41QbCzsbzEgeK5ul/MbFOCUPd2gUqzAedrNmW6NVWkxrBipVKB/jR8jxdjc2lglLpQ62gBUYchIUdjIn2Zk09sIu/K42LC9cLJnBfVAoYDjC8lJNEK2gcqSWVX2iCBC24DJprEw6GqczNS9cz3Hieet7vzWm4jv5QtjCaSyv5TpUF7Vg+QFOsT3aZQGIwvRwgRCtM+k69QknDpZj45Z8qu0JrABs3yGbzeL3djDy+iSpfIJMxsUdy4braNYnsViAn3axPR862qHZsyAb/0jIZsOZofVZn3N+bE5dmTNKYSdzmv3SQLiQ8Ensgn08Ji06fJTXbEwScdqzB/d6mzA+FQVQvXvQSrhhFx5EW/oYz4ORclin5vtYfpog5VBra8XpPIvRZSlqWYvsKz5tz4/gb98x5bX4o4WwSN11sF0bvzVBrc3FLfnU2g2WD4Fr0dnbQam/lSBpUe4EP5mklk1iV7P0/GI4vKZ0EssLCLKpgzssHM7EGZaND/qpHmvcE9cl6O08+H2xjJkwuzOOotargnBaKexkTmqsMXncRdfN0GhFHaNGjVtUalA7uEyYxYRW6MR6vnSqPrYXBqRdrmJyWeyKh58Jj3vlnWnKy6pQtql0uNhejvRzh2k9BH4UeDZgtadxSz5OsUZiNB0t/Oy3JEkUPOyqg+WHiz/XshaJgglr7BoF7/Wd261y7Ygf0na9RQtE46jRtj2ed9jWmuWFu8NbhXGCU/3/ebpaYEdYVk5BN/0UdjJnzUTQmZoHbfVJJFNsS3O0n40+2BpjdPWxPVPzcBJhLZ+VTh/ceufQ2ZllD6fkYTs25UUepy/ZS9L22dnaQ/WFJFNs8XpQfYNaJ5ul2pEIlyjLOHT8u0+p08apEq2Bmcob/GS4GJhdPXgKqzCOKZdx6sXl5kgLVdtOuFN5rr69Ub2FNmnD2Yn/D+slGE6+vtO55+OfyCoys9WhO2o0QlVBd0oo7ESOQ/RBXe96nGoftkOPN5732in0jaXEJmjsxN1oDVnp9ITdAYrQmiFIu1heQGLPAfoe6mdXeRFmQZXMr9K0/3rsmD84q202ftLCLVl0bN5JW6mMtagHvzOLOxrgjicpdyfxkxb9Px3BzhejlV1MzcN/+ZVjuldBV3u0O7t17huodaTDSTGVAKfkhTWLdXYmXLnF23X0czfVoS256QqfQ8+rkDulFHYy98zgQL+pedHEEyvhQukoxx9vq6Te+rI8L+xubJQslMrYxRI2YcE35Qq5HWNYfhvGSZLbkcd+aeDIhe6N6y+XSY34+CkbdzycSBOUyjgjo+G4nudj5x3sSjbckXxwOCwxqK8E05hleiwsL4BwPg+V7gxei4NxwGuxSbgW6fpYZWPs0kq49d3Lp2+C0WsodOYFhZ3MPUf5cDrW/eZO9LUbrS5TLjenxGGK1zAVf9IEGFOpHFwVpX4MA4O0PVFv+R1tRZcJ5/b37Se9ub7014S6N3/f/mgZrwbHdvAOnVhyjPfUVCowuA+3XjdXXHo6tYyNn4R0PsAd97FOX4xxw+XIGjsq2IBfmzApZeI/bjSjUU6Qwk7ixXYmFXBPy/kb3YvHOVGlKZrUFXbMLc6T7N6LWsGuS+qAR+AkMI6FOx6QGB6n2lPfQT3jkHRtEnl38j1V1580icJO4mPCXnHTeW6TToLjHHW8rvFzwPz8kLYd/PPfQP71LdSy0PayT9uLRby2JImRMtb+EfzFbRjHwk+FC06bdPKk97gTmYrCTmZekwIhmuZeH/sx7hQTQ06Q0549OK7k+VAYP2rryEqlwkLxhHvEHc1jyXZwzljO8F8UWdgyRNL2eGrXYnp+1Ernz/dgUkm8pT2k9pUIUuGkG6dYhX3Dh71Pdmtr2IWcbQ3LMspVvGOYKDNrzed/CM0AhZ3MCs0Y+2rUc02czt8UtjO5Jm4kf0znbgQdNOf9zSVWwsXPZcgkRjmrbZBKkOCJqhOWM3g+Xn8rfsbFCgyWZ7ArHrwyEP6j4HDnzKShawFeLlzJxSlWsQ+0xmexaFAATiOFncwKzQimYKwQLbll1b9vRsBE5QON7rXiMZyz3u3ZWBElnHQxf4qHTc3D3v4Cr2x7EwOvbyfXWsI54NK2u4opl8Mly1yLWpuLUzEkAatRfO8erBacGGSW62JcJ2wJ+kG4s3smfXz1jrNpgsvJ7KhxqNn0vmYphZ2cOof5hbQSblPCLmpJeQdXKGmGaAftE5mgUZ+yf0zje3FSL6FYsqnK3qE2hnuydG2H5L5xTKmMM14lSKZJjPnY9ZZdY5UZs6w/3PG8Up103/wDIzhAAqJ6Q3Os93XimGvcWtgnsOntfKSwk1PjCGHRWE7rZD+Eoq1vjrIo8gk5gXMFpXK40kpthpY1mwVST/2G0/b1UOvMkNo5iCkUCDwPOz9O0guodWZIDJfCZcdcF3q7qXa3AIS7LhSK9RZ6JSxmPzCC7Xk49d0fvOOYzBJtnRTHFnbc3s80UNjJqXGkX8aptn85gZaUqVRmT6jU39OsuZ6Z0NjLbt9+HGBiO9v/9YtgOyQaReUAvQsZX9ZOYZGLU4X0iEMincYGvAvPxs+44aorT/168n6Fx/J3pVGsn3BnTzDUW5sn/XdktryfWU5hJ7OTfoHjrx5AjVVonNP6wsWpqy7JQlh0btJJihecxtBbXGrtAR3PJund1YGVqK+zmQ6XGPMPKYY/3OuZ2jS+nxNwyus05zGFnYjMnAn/qLGKJZJD0JK0SYzVcIpVxs/sZvelFgtO30fCCdjvL6T7yQ7sXJZaZwtei0PmNyNYY4Vj656cTf+ImupaNBtz2ijsRGRW8H6zC2yH1K/DjyV7QQeDly9gxXkv8oeLHmH7+Gl8a6CDl9fkCBIQJA3GgZYzelh0f7j1kBnJR+ULEyc+TZoENYuDpLEYduwm0cwCCjsRmT3qXY2NcbwgaSjWkmwfP40XxruxR12CBFQXBPiZAGxwSi5+Z7iNkOM6WPWJQY1FpaG+h16GWb/j+QmtHqOyg2OisJNTQ7+QcqzqgWfKZZb83wq76edf3pSitLUbJ2uoLgiwfAsSBqts445DpTuNUwmwK2mcBR2Yrg68XJpaW4LMy2PhRrBegFMshVsIzdK/i0edsDLV79Hh3ssRdoSfjxR2cmrol02OR33ySuq5V1hW6WP8iQUU32TwWgPSg+GHuJe1SIzaZF8JsHyDO1bF3j/K+PlLGF2WwMtY2D441Vbsih/W8rmt9S5NZt/fyfpKPUd0nNfclNmeMaGwk1NHg+9yHEylEhaSP1Wg/fk0Y6edhXFsEmOQKBj8jEPLqxate8KuP2e4gCmX2fvmJLV2g58OSIzalLsSZAZNuPKKE2C74U7zUZfhbPn7OA3bUc222aczSWEnp85s+VCROSOqnSyVWfz/vYRpzWAVSwQHRlgIBG98HUHKJTE0BsDgB86keFaVzoWjjI61wGgL7nhAqTeJUzG07Bo7uF6pNw9aPfqdiyjsRGT2C3z8vfuwDrj4pYOTTpzhAk4qCfsP4J25mOJiOK1/mI50ibFiGrsKTiVg+OwEThUShQzJlyac93C9DTM5xtysYnOZRGEnInPCoSvkBKUy9qtDGM8Lp+w7Nqn9FkMjWeiAZNKn+6kae89PUVwakNthhUuTZbOUz+ojcC1S+0o4r+zDG9p30hvVNsV07sk4z+muisjc1FiBJfAxrkvi1RE6f+Uw4mfZ35XFrkJq3xjGSWAcQ6JgYeeLVM7oZe/5KQByLzq0lT2sAyOzZtKKVlWZHvZ0nPSVV17hj/7oj+jq6iKTyXDeeefx2GOPRc8bY7jppptYtGgRmUyGNWvWsHPnzknnGB4eZt26dbS3t9PR0cHVV19NoXD4va5EZB6qh1NQKmNeHaJlxxA9j4xx+vcOsOwH+7H8gETBkNvh0PZyBVMosv+NaYpLAwrLffLLHSp92Rl+E1OYBaEbN01v2R04cICLLrqId73rXfz4xz9m4cKF7Ny5kwULFkTH3Hrrrdx2223cddddLF++nBtvvJG1a9fy7LPPkq7v/7Vu3TpeffVVNm3aRK1W40Mf+hDXXHMN99xzT7MvWUTmusAnKBbD/e9+A0F9LM7OpFm0vwtTKIbbASVcRs71SHSU8SoupT6bfD5J109myU4Iga8te6aJZYwxzTzh9ddfz89+9jP+7d/+bcrnjTH09/fziU98gk9+8pMA5PN5ent7ufPOO7nyyit57rnnWLFiBY8++igrV64E4P777+e9730vL7/8Mv39/a85b6VSoTKhP390dJQlS5bw27wf10o08y2KyFxRD47GOJidSfP8jedgeisEhQSpIYfuXwa0fvex4w87LZQwrTxT46d8n3w+T3t7+0mfr+ndmD/4wQ9YuXIlf/AHf0BPTw8XXHABX//616PnX3zxRQYGBlizZk30WC6XY9WqVWzZsgWALVu20NHREQUdwJo1a7Btm61bt075uhs3biSXy0VfS5YsafZbE5G55tAwcl1aXrFxX0pj1SzsqkViLDzGSqWwUqnjO79aYXNG08PuhRde4Pbbb+eMM87gX/7lX/jIRz7Cn//5n3PXXXcBMDAwAEBvb++kn+vt7Y2eGxgYoKenZ9LzruvS2dkZHXOoG264gXw+H33t3r272W9NROaiwMfUwg19g7ECix4eo+uXhuyLDguf8mjZMYS79DTsJf04CzqOPcACXy27OaTpY3ZBELBy5Uq++MUvAnDBBRfwzDPPcMcdd3DVVVc1++UiqVSK1PH+q0xE5ocolFzcPcO0+wHZ3S6JXfsw5TLBsj6g/q//AQVYHDW9Zbdo0SJWrFgx6bFzzjmHXbt2AdDXF/6lGhwcnHTM4OBg9FxfXx9DQ0OTnvc8j+Hh4egYEZHjZSoVvD0DmCd+hfWLZ/D2DGBlWzFO+FFoeeEEkePuzpRZr+lhd9FFF7Fjx45Jjz3//PMsW7YMgOXLl9PX18fmzZuj50dHR9m6dSurV68GYPXq1YyMjLBt27bomAceeIAgCFi1alWzL1lE5pNDuh7NSD5ciWVwhGBvuOO5at3ip+ndmB//+Md5xzvewRe/+EX+03/6TzzyyCN87Wtf42tf+xoAlmVx7bXX8oUvfIEzzjgjKj3o7+/n8ssvB8KW4Lvf/W4+/OEPc8cdd1Cr1diwYQNXXnnllDMxRUSOSyPwbIegVMZ6dShchqxZy4Zppuas0/Swe+tb38q9997LDTfcwF/91V+xfPly/vZv/5Z169ZFx3z605+mWCxyzTXXMDIywsUXX8z9998f1dgB3H333WzYsIFLLrkE27a54ooruO2225p9uSIynwU+puIffh1KBVZsNL3ObrYYHR0ll8upzk5ETpxaaDNm1tfZiYjEhoIuNhR2IiLTSYXns4LCTkTkZB0t0GxHoTfDFHYiIs1wuDBrdIXOhi7ReRy62s9ORKQZjhRmsyHoJpoYeLPt2qaJWnYiIidrDgbGfNsRfX69WxGRuaaZ5Q8TzmNqzTnlXKGWnYjIbHYsQXei43BzsEV6otSyExGZa2wn6oY84XU851HQgVp2IiInZwZmN1oJF8tVW+V4KOxERE5EfRq/lXBnJPCMN6FFN89aaSdC/zQQETketoOdSU+azWhcj2CqXROmyWEXrpbDUstOROQ4WQkXK5uFelfipFbWRPO0gHs2UstOROQ4mZqHVQ+4oFSOWlpWKoXluliZNKZUxnheOMVf3YwzTmEnInKcglIZCFt0UZei7eAs6g0fdx1s1yUYK2jX81lCYScicjwCP9rhvNFiczpycFof44vbcMd9LD/ABaxyGUoze7kSUtiJiByvCd2SVirF+DvOJP+6BF4GUsOGtpdruPnka44FDo7jqWvzlNIEFRGRE2SlUjgLOvBTNoED1oT8svKFqLtTZp7CTkTkZLguyVGPRMHgVCGdD0jtK+Hv3ffaEgG16maMujFFRE6QqXmYcpnUQIGel33YfyCclHK4OjiF3IxR2ImInKjAJxgr4LguxvPwh0eOHGjN3MGgmWbrdTWRwk5E5CSYSgVvYPDIB83G7st5toGrwk5EZDodbhWVGQzARvF7WPQ+P+oAFXYiItPpMKUHdiZdL0qf4VbVPGjVgcJORGRGnMqFow9lKpWwRTdPgg4UdiIip9ZsCZjZch2niMJORORUOHR38ZkIm3kw6/JwVFQuInIKWAkXO5OeuQuY59sNKexERKZbPWhmfObjVK26+o7rcaduTBGR6Rb4mIo/u3YYr3erWvUNaINi8aTONdu7RxV2IiLzxRShdNhd1o/HLA86UNiJiMwLVsKd3I0a+OEu6vU/x53CTkQk5qxUauoZoPMg5BoUdiIip8IMrkU54xNjZgGFnYjINLJSKYCo7CAolcPuw3rgHbbV1UzzqAV3OCo9EBGZLvXWnOUeHC+zXDcsLp+pKf/zoMxgKmrZiYicIqbmTdpp4DWTRqbTPA25BoWdiMh0adTXNbop67VtTnsWqyMHgP/qYPj8HKhVm8sUdiIi060eYm5PN6arA781iXFt7IqHXSgSjBWwXPfkCruP8RrmK4WdiMh0sh2cM5ZTWZxj5+UuptUH36LjqQRd28uksq1YpXK45Y9MG01QERGZDvUJKFbCpXhmJ8PnpDCtPnbSx854lLug3JWAcqU5q5gc7hoEUMtORGTaNHY6KHU5eBlIvprAT4cfu5YPgWPhHxiJjp1YkiDNpbATEZkmluuC69L6ao3ASZDZC6m8AcAdr5L5zQhk0uC6mFK5+TMzFZwRhZ2IyHTyPNIDRZxqBj9pkxir4e4vwv4DBGMF7LYsELbsKCqcpovCTkRkmjTG4qxXhkjtT4PrQLlCMFaIZl6aepG5lvSaXgo7EZHpUN9VwNQ8aMy0nKJbcVrLDabSmLQyz7o4FXYiItPlGAIlWhvzGI8/YY2lyxLu7NpE9hRR2ImInGr1kgQ7k8ZKpzGeRzBWwFSOEnb1wHI6OwAwjfq8YwnJwI8WpZ6PFHYiIqdSPegs9+DHr+WG3x+xxWU7uD3d4Z/TKfB88DwoHftLm0pl3tbeqahcRGQGWIkw7IznRV+H3QnBdnDaswS9nZiujvAx18FKp4+/63OejdU1KOxERGaAqXlhF6TnYaXTOIt6owCcyEqlwu7OjhzV7hZqnS2YVBI8vzkrr8yTlp66MUVETjFTC7f5aYSYSSWByfveAWGXZ2P/u3IFuxqEj/s+plA4qXKFxvjdfNlxQWEnInKKWQkXZ2E3pjWD8es7lleqkHAnj8E1Aqg+vpd4bheW6+IfGDm5GZUTNpW1XHdeLEKtsBMRmQmuE35RD7pyZcqWmvHCOj0DB0Opia2wY57NOccp7EREZoLnh19++F9TnrqMoNHlaSXcpofSfAk6UNiJiJxa9ZVV/L37YG/4ULST+WGOB45eg3e819DM880BCjsRkVPtSGEzDyaLzASVHoiIzBbzpAxgJqhlJyIyW0zVopsYgGrxnTC17EREJPbUshMRmc2a2JqbVEg+z1qJTW/Z+b7PjTfeyPLly8lkMrz+9a/n85//PMaY6BhjDDfddBOLFi0ik8mwZs0adu7cOek8w8PDrFu3jvb2djo6Orj66qspFArNvlwRkbmhCeN5jTKG+RZ0MA1h99d//dfcfvvt/P3f/z3PPfccf/3Xf82tt97Kl7/85eiYW2+9ldtuu4077riDrVu30traytq1aymXD1bxr1u3ju3bt7Np0ybuu+8+HnroIa655ppmX66IyNzQjIAK/MOfJ+aTYywzscnVBL/7u79Lb28v//iP/xg9dsUVV5DJZPjmN7+JMYb+/n4+8YlP8MlPfhKAfD5Pb28vd955J1deeSXPPfccK1as4NFHH2XlypUA3H///bz3ve/l5Zdfpr+//6jXMTo6Si6X47d5P66VaOZbFBGZ2+bApBfP1Pgp3yefz9Pe3n7S52t6y+4d73gHmzdv5vnnnwfgqaee4uGHH+Y973kPAC+++CIDAwOsWbMm+plcLseqVavYsmULAFu2bKGjoyMKOoA1a9Zg2zZbt26d8nUrlQqjo6OTvkREZr3Gtj4Tv6b59abaXSHumv6Or7/+ekZHRzn77LNxHAff97n55ptZt24dAAMDAwD09vZO+rne3t7ouYGBAXp6eiZfqOvS2dkZHXOojRs38rnPfa7Zb0dEZHpM2K28seblyexicEJmaatuOjS9ZffP//zP3H333dxzzz08/vjj3HXXXfzP//k/ueuuu5r9UpPccMMN5PP56Gv37t3T+noiIieqsUed3ZbFSof/tTPpI4+pNUvghzsmzKOgg2lo2X3qU5/i+uuv58orrwTgvPPO46WXXmLjxo1cddVV9PX1ATA4OMiiRYuinxscHOTNb34zAH19fQwNDU06r+d5DA8PRz9/qFQqRao+rVZEZLayUqlojzpTKofb+sC82GZnJjW9ZTc+Po5tTz6t4zgEQbjp4PLly+nr62Pz5s3R86Ojo2zdupXVq1cDsHr1akZGRti2bVt0zAMPPEAQBKxatarZlywicsqYSoWgVMYfLYT/Hcnjj+RPbn+6k3GqxgpnWNNbdu973/u4+eabWbp0KW984xt54okn+NKXvsSf/MmfAGBZFtdeey1f+MIXOOOMM1i+fDk33ngj/f39XH755QCcc845vPvd7+bDH/4wd9xxB7VajQ0bNnDllVce00xMEZFZ7dAuxEbQzGTXYsy7NZsedl/+8pe58cYb+bM/+zOGhobo7+/nv/23/8ZNN90UHfPpT3+aYrHINddcw8jICBdffDH3338/6XQ6Oubuu+9mw4YNXHLJJdi2zRVXXMFtt93W7MsVEZlRdmtr9OcZ2V8u5iHX0PQ6u9lCdXYiMhs1xuyqbz8br8WhZdcYdr4Ino+3Z2DehM/RNLvObv4VW4iIzBCnI4fVkcOkkoz3JqhlLBKFDMliGascjtlF61fO1BheTCnsRESmW6OQ+7Q+Kj2teBmHwLEwDjjFGlZhnGCsMC+LvU8V3VkRkVPEuDaWZ3BLPtk9AX7KxhkuEIyFi9ybmqfAmya6qyIip4hVLOMCQcrFHcoD4L86OGnllFO+iso8obATETkFTM3Df2FX9L2niSinlMJORGS6HS3Y6nV2E7swNUGluRR2IiIzacIuBJYb/td4XhiAav01jcJORGQGHRp00RqZCrqmUtiJiMwgU6lE3Zim5inkponCTkRkpgU+pqKQm05N3/VARERmuSl2OLBSqXD1lpjufqCWnYjIbHAqJ6RMsetCY8wQiGUrU2EnIjIbnMqxugnB2liY2nhhMXtcSx7UjSkiMs/YmfSk7krjeZhKJbZBB2rZiYjML7ZDUCxG38Y54CZSy05EZD6Zp6UNCjsREYk9hZ2IiMSewk5EZL6LaW3dRAo7EZH5bh6M4ynsRETkqOb66ioqPRARkSObsMKKqTEnW4IKOxEROaq5vvWQwk5ERA6v0XU5R0OuQWEnIiKHN8dDrkFhJyIynWwHK+GG61G6LqZUDrsEYxIic4XCTkRkOjRCri0LnoeVDsMOz8Py3FhuozObKexERKaBnUljt2Ux2ZbwgXIVk05ieWlswJ8nCzDPFqqzExGZJsbzsDwfUklwHaxyNdxOp+Yd+QfncD3bbKWwExFpNtvByqRf87Apl8Hzoo1SD/ez0nzqxhQRaSK7tRV7QQdBVzuWF0CxhLV/BON5BGOFsFV3uMkpcznoZnmJgsJORKRJnI4cdHdiUkmq3S3Y1YCE50Mh3Cz1iEEHszYojpWVmL0TbxR2IiLNYDuYZf1Uu1vwWsJWju1aJFwHUypjJdw5H2ZHc9SxyBmksBMROVm2g51JU+1uobLAxfLBHfdJHqhg5Qv4xeJxnWvGQ/FErmGmr/koFHYiIifJSrjhV2BwKga7GpDaV8LOjxMcGDm+k810aDTG3mZD6DaRwk5E5CSZmkdAmdRzr5BKp6BcwRvah39oWMzySRzA7L62k6CwExFpAlPz8Ce24qYKjaMFycTZmDENnZmisBMROVn1YGraTEQFXdOpqFxEZLYI/JkPurlc63cECjsREZkb44knQWEnInIq2c7sbD3FNOQaNGYnInIqxTxUZiu17EREJPYUdiIiEnvqxhQRaTbVy806CjsRkWapr5EJYGXSmFKZoFRW4M0CCjsRkZNlOzjtWbwVp+M5NpYfkHhhABIuljd7t72ZTzRmJyJyMhqtOdfF8gKMaxGkHEy2BVPzjr7tzWwsQ4ghtexERE6SlUljuS7OcAHLbwlD79UhgmPZ2kddnKeEwk5E5GQEPsFYAct1scpl7JFR8Lzj28NOpp3CTkTkJEXdlUW10mYrhZ2IyMlSV+SspwkqIiISewo7ERGJPYWdiIjEnsJORERiT2EnIiKxp7ATEZHYU9iJiEjsKexERCT2FHYiIhJ7xx12Dz30EO973/vo7+/Hsiy+973vTXreGMNNN93EokWLyGQyrFmzhp07d046Znh4mHXr1tHe3k5HRwdXX301hUJh0jG//OUv+a3f+i3S6TRLlizh1ltvPf53JyIiwgmEXbFY5Pzzz+crX/nKlM/feuut3Hbbbdxxxx1s3bqV1tZW1q5dS7lcjo5Zt24d27dvZ9OmTdx333089NBDXHPNNdHzo6OjXHrppSxbtoxt27bxN3/zN/yP//E/+NrXvnYCb1FEROY7yxhjTviHLYt7772Xyy+/HAhbdf39/XziE5/gk5/8JAD5fJ7e3l7uvPNOrrzySp577jlWrFjBo48+ysqVKwG4//77ee9738vLL79Mf38/t99+O5/97GcZGBggmUwCcP311/O9732PX/3qV8d0baOjo+RyOX6b9+NaiRN9iyIiMgM8U+OnfJ98Pk97e/tJn6+pY3YvvvgiAwMDrFmzJnosl8uxatUqtmzZAsCWLVvo6OiIgg5gzZo12LbN1q1bo2Pe+c53RkEHsHbtWnbs2MGBAwemfO1KpcLo6OikLxEREWhy2A0MDADQ29s76fHe3t7ouYGBAXp6eiY977ounZ2dk46Z6hwTX+NQGzduJJfLRV9Lliw5+TckIiKxEJvZmDfccAP5fD762r1790xfkoiIzBJNDbu+vj4ABgcHJz0+ODgYPdfX18fQ0NCk5z3PY3h4eNIxU51j4mscKpVK0d7ePulLREQEmhx2y5cvp6+vj82bN0ePjY6OsnXrVlavXg3A6tWrGRkZYdu2bdExDzzwAEEQsGrVquiYhx56iFqtFh2zadMmzjrrLBYsWNDMSxYRkXnguMOuUCjw5JNP8uSTTwLhpJQnn3ySXbt2YVkW1157LV/4whf4wQ9+wNNPP81//a//lf7+/mjG5jnnnMO73/1uPvzhD/PII4/ws5/9jA0bNnDllVfS398PwH/5L/+FZDLJ1Vdfzfbt2/mnf/on/u7v/o7rrruuaW9cRETmD/d4f+Cxxx7jXe96V/R9I4Cuuuoq7rzzTj796U9TLBa55pprGBkZ4eKLL+b+++8nnU5HP3P33XezYcMGLrnkEmzb5oorruC2226Lns/lcvzrv/4r69ev58ILL6S7u5ubbrppUi2eiIjIsTqpOrvZTHV2IiJzV7Pr7I67ZTdXNDLcowaxjHMRkfjyCOdsNKs9Ftuw279/PwAP86MZvhIRETlRY2Nj5HK5kz5PbMOus7MTgF27djXlRsXN6OgoS5YsYffu3SrTmILuz9HpHh2Z7s+RHe3+GGMYGxuLJi6erNiGnW2HE01zuZz+oh2BahKPTPfn6HSPjkz358iOdH+a2VCJzQoqIiIih6OwExGR2Itt2KVSKf7yL/+SVCo105cyK+n+HJnuz9HpHh2Z7s+Rner7E9s6OxERkYbYtuxEREQaFHYiIhJ7CjsREYk9hZ2IiMSewk5ERGIvtmH3la98hdNPP510Os2qVat45JFHZvqSpt3GjRt561vfSltbGz09PVx++eXs2LFj0jHlcpn169fT1dVFNpvliiuueM2u8Lt27eKyyy6jpaWFnp4ePvWpT+F53ql8K6fELbfcEu3B2DDf788rr7zCH/3RH9HV1UUmk+G8887jsccei543xnDTTTexaNEiMpkMa9asYefOnZPOMTw8zLp162hvb6ejo4Orr76aQqFwqt/KtPB9nxtvvJHly5eTyWR4/etfz+c///lJixXPp3v00EMP8b73vY/+/n4sy+J73/vepOebdS9++ctf8lu/9Vuk02mWLFnCrbfeevwXa2Lo29/+tkkmk+Z//+//bbZv324+/OEPm46ODjM4ODjTlzat1q5da77xjW+YZ555xjz55JPmve99r1m6dKkpFArRMX/6p39qlixZYjZv3mwee+wx8/a3v9284x3viJ73PM+ce+65Zs2aNeaJJ54wP/rRj0x3d7e54YYbZuItTZtHHnnEnH766eZNb3qT+djHPhY9Pp/vz/DwsFm2bJn54z/+Y7N161bzwgsvmH/5l38xv/71r6NjbrnlFpPL5cz3vvc989RTT5nf+73fM8uXLzelUik65t3vfrc5//zzzS9+8Qvzb//2b+YNb3iD+cM//MOZeEtNd/PNN5uuri5z3333mRdffNF85zvfMdls1vzd3/1ddMx8ukc/+tGPzGc/+1nz3e9+1wDm3nvvnfR8M+5FPp83vb29Zt26deaZZ54x3/rWt0wmkzH/8A//cFzXGsuwe9vb3mbWr18ffe/7vunv7zcbN26cwas69YaGhgxgHnzwQWOMMSMjIyaRSJjvfOc70THPPfecAcyWLVuMMeFfXtu2zcDAQHTM7bffbtrb202lUjm1b2CajI2NmTPOOMNs2rTJ/If/8B+isJvv9+czn/mMufjiiw/7fBAEpq+vz/zN3/xN9NjIyIhJpVLmW9/6ljHGmGeffdYA5tFHH42O+fGPf2wsyzKvvPLK9F38KXLZZZeZP/mTP5n02Ac+8AGzbt06Y8z8vkeHhl2z7sVXv/pVs2DBgkm/X5/5zGfMWWeddVzXF7tuzGq1yrZt21izZk30mG3brFmzhi1btszglZ16+XweOLgDxLZt26jVapPuzdlnn83SpUuje7NlyxbOO+88ent7o2PWrl3L6Ogo27dvP4VXP33Wr1/PZZddNuk+gO7PD37wA1auXMkf/MEf0NPTwwUXXMDXv/716PkXX3yRgYGBSfcnl8uxatWqSfeno6ODlStXRsesWbMG27bZunXrqXsz0+Qd73gHmzdv5vnnnwfgqaee4uGHH+Y973kPoHs0UbPuxZYtW3jnO99JMpmMjlm7di07duzgwIEDx3w9sdv1YN++ffi+P+nDCKC3t5df/epXM3RVp14QBFx77bVcdNFFnHvuuQAMDAyQTCbp6OiYdGxvby8DAwPRMVPdu8Zzc923v/1tHn/8cR599NHXPDff788LL7zA7bffznXXXcd//+//nUcffZQ///M/J5lMctVVV0Xvb6r3P/H+9PT0THredV06Ozvn/P0BuP766xkdHeXss8/GcRx83+fmm29m3bp1ALpHEzTrXgwMDLB8+fLXnKPx3IIFC47pemIXdhJav349zzzzDA8//PBMX8qssXv3bj72sY+xadMm0un0TF/OrBMEAStXruSLX/wiABdccAHPPPMMd9xxB1ddddUMX93s8M///M/cfffd3HPPPbzxjW/kySef5Nprr6W/v1/3aJaLXTdmd3c3juO8Zgbd4OAgfX19M3RVp9aGDRu47777+MlPfsLixYujx/v6+qhWq4yMjEw6fuK96evrm/LeNZ6by7Zt28bQ0BBvectbcF0X13V58MEHue2223Bdl97e3nl9fxYtWsSKFSsmPXbOOeewa9cu4OD7O9LvVl9fH0NDQ5Oe9zyP4eHhOX9/AD71qU9x/fXXc+WVV3LeeefxwQ9+kI9//ONs3LgR0D2aqFn3olm/c7ELu2QyyYUXXsjmzZujx4IgYPPmzaxevXoGr2z6GWPYsGED9957Lw888MBrmv4XXnghiURi0r3ZsWMHu3btiu7N6tWrefrppyf9Bdy0aRPt7e2v+SCcay655BKefvppnnzyyehr5cqVrFu3LvrzfL4/F1100WtKVZ5//nmWLVsGwPLly+nr65t0f0ZHR9m6deuk+zMyMsK2bduiYx544AGCIGDVqlWn4F1Mr/Hx8Whj6AbHcQiCANA9mqhZ92L16tU89NBD1Gq16JhNmzZx1llnHXMXJhDf0oNUKmXuvPNO8+yzz5prrrnGdHR0TJpBF0cf+chHTC6XMz/96U/Nq6++Gn2Nj49Hx/zpn/6pWbp0qXnggQfMY489ZlavXm1Wr14dPd+YWn/ppZeaJ5980tx///1m4cKFsZhaP5WJszGNmd/355FHHjGu65qbb77Z7Ny509x9992mpaXFfPOb34yOueWWW0xHR4f5/ve/b375y1+a97///VNOJb/gggvM1q1bzcMPP2zOOOOMOTmtfipXXXWVOe2006LSg+9+97umu7vbfPrTn46OmU/3aGxszDzxxBPmiSeeMID50pe+ZJ544gnz0ksvGWOacy9GRkZMb2+v+eAHP2ieeeYZ8+1vf9u0tLSo9KDhy1/+slm6dKlJJpPmbW97m/nFL34x05c07YApv77xjW9Ex5RKJfNnf/ZnZsGCBaalpcX8x//4H82rr7466Ty/+c1vzHve8x6TyWRMd3e3+cQnPmFqtdopfjenxqFhN9/vzw9/+ENz7rnnmlQqZc4++2zzta99bdLzQRCYG2+80fT29ppUKmUuueQSs2PHjknH7N+/3/zhH/6hyWazpr293XzoQx8yY2Njp/JtTJvR0VHzsY99zCxdutSk02nzute9znz2s5+dNC1+Pt2jn/zkJ1N+5lx11VXGmObdi6eeespcfPHFJpVKmdNOO83ccsstx32t2s9ORERiL3ZjdiIiIodS2ImISOwp7EREJPYUdiIiEnsKOxERiT2FnYiIxJ7CTkREYk9hJyIisaewExGR2FPYiYhI7CnsREQk9v5/GQ9UYCOjbkMAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.imshow(img_proj_norm)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc9da43d-35c6-4ec3-a4cf-050670b12d2f",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "765e03a2-1b27-4f74-a1a8-154c59bbc527",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "2d21905f-f7c5-4083-812d-906a5737e2ba",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-27 14:05:44.456906: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.457910: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.458645: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.459345: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.460049: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.460756: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.461471: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.462227: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.462930: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.463632: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.464323: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.465017: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.465845: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 14:05:44.465860: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 14:05:44.465931: W tensorflow/core/kernels/conv_ops_gpu.cc:144] None of the algorithms provided by cuDNN frontend heuristics worked; trying fallback algorithms.  Conv: batch: 1\n",
      "in_depths: 1\n",
      "out_depths: 32\n",
      "in: 1024\n",
      "in: 1024\n",
      "data_format: 1\n",
      "filter: 3\n",
      "filter: 3\n",
      "filter: 1\n",
      "dilation: 1\n",
      "dilation: 1\n",
      "stride: 1\n",
      "stride: 1\n",
      "padding: 1\n",
      "padding: 1\n",
      "dtype: DT_FLOAT\n",
      "group_count: 1\n",
      "device_identifier: \"sm_6.0 with 12786073600B RAM, 56 cores, 1328500KHz clock, 715000KHz mem clock, 3145728B L2$\"\n",
      "fusion {\n",
      "  activation_mode: kRelu\n",
      "  conv_scale: 1\n",
      "}\n",
      "version: 3\n",
      "\n",
      "2024-03-27 14:05:44.466999: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.467718: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:753] failed to allocate 22.36MiB (23448576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory\n",
      "2024-03-27 14:05:44.468530: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:190] failed to create cublas handle: the resource allocation failed\n",
      "2024-03-27 14:05:44.468545: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:193] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n",
      "2024-03-27 14:05:44.468980: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at conv_ops_fused_impl.h:625 : NOT_FOUND: No algorithm worked!  Error messages:\n",
      "  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n",
      "  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[13], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m img_norm \u001b[38;5;241m=\u001b[39m normalize(img_zoom, \u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m99.8\u001b[39m)\n\u001b[0;32m----> 2\u001b[0m img_proj_pred \u001b[38;5;241m=\u001b[39m \u001b[43mget_mask_from_proj_pred\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel_2D\u001b[49m\u001b[43m,\u001b[49m\u001b[43mimg_zoom\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py:111\u001b[0m, in \u001b[0;36mget_mask_from_proj_pred\u001b[0;34m(model_2D, img_zoom)\u001b[0m\n\u001b[1;32m    109\u001b[0m img_proj \u001b[38;5;241m=\u001b[39m  np\u001b[38;5;241m.\u001b[39mmax(img_zoom,axis \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m)\n\u001b[1;32m    110\u001b[0m img_proj_norm \u001b[38;5;241m=\u001b[39m normalize(img_proj)\n\u001b[0;32m--> 111\u001b[0m img_proj_pred,_ \u001b[38;5;241m=\u001b[39m \u001b[43mmodel_2D\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mimg_proj_norm\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    112\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m img_proj_pred\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:777\u001b[0m, in \u001b[0;36mStarDistBase.predict_instances\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    764\u001b[0m \u001b[38;5;129m@functools\u001b[39m\u001b[38;5;241m.\u001b[39mwraps(_predict_instances_generator)\n\u001b[1;32m    765\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_instances\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    766\u001b[0m     \u001b[38;5;66;03m# the reason why the actual computation happens as a generator function\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    774\u001b[0m \n\u001b[1;32m    775\u001b[0m     \u001b[38;5;66;03m# return last \"yield\"ed value of generator\u001b[39;00m\n\u001b[1;32m    776\u001b[0m     r \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m--> 777\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_instances_generator(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    778\u001b[0m         \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[1;32m    779\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m r\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:729\u001b[0m, in \u001b[0;36mStarDistBase._predict_instances_generator\u001b[0;34m(self, img, axes, normalizer, sparse, prob_thresh, nms_thresh, scale, n_tiles, show_tile_progress, verbose, return_labels, predict_kwargs, nms_kwargs, overlap_label, return_predict)\u001b[0m\n\u001b[1;32m    727\u001b[0m res \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    728\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m sparse:\n\u001b[0;32m--> 729\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m res \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_predict_sparse_generator(img, axes\u001b[38;5;241m=\u001b[39maxes, normalizer\u001b[38;5;241m=\u001b[39mnormalizer, n_tiles\u001b[38;5;241m=\u001b[39mn_tiles,\n\u001b[1;32m    730\u001b[0m                                               prob_thresh\u001b[38;5;241m=\u001b[39mprob_thresh, show_tile_progress\u001b[38;5;241m=\u001b[39mshow_tile_progress, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mpredict_kwargs):\n\u001b[1;32m    731\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m res \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    732\u001b[0m             \u001b[38;5;28;01myield\u001b[39;00m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtile\u001b[39m\u001b[38;5;124m'\u001b[39m  \u001b[38;5;66;03m# yield 'tile' each time a tile has been processed\u001b[39;00m\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:592\u001b[0m, in \u001b[0;36mStarDistBase._predict_sparse_generator\u001b[0;34m(self, img, prob_thresh, axes, normalizer, n_tiles, show_tile_progress, b, **predict_kwargs)\u001b[0m\n\u001b[1;32m    588\u001b[0m         \u001b[38;5;28;01myield\u001b[39;00m  \u001b[38;5;66;03m# yield None after each processed tile\u001b[39;00m\n\u001b[1;32m    590\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    591\u001b[0m     \u001b[38;5;66;03m# predict_direct -> prob, dist, [prob_class if multi_class]\u001b[39;00m\n\u001b[0;32m--> 592\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[43mpredict_direct\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    593\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m results[:\u001b[38;5;241m2\u001b[39m]\n\u001b[1;32m    594\u001b[0m     prob, dist \u001b[38;5;241m=\u001b[39m _prep(prob, dist)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/stardist/models/base.py:398\u001b[0m, in \u001b[0;36mStarDistBase._predict_setup.<locals>.predict_direct\u001b[0;34m(x)\u001b[0m\n\u001b[1;32m    397\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mpredict_direct\u001b[39m(x):\n\u001b[0;32m--> 398\u001b[0m     ys \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeras_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[43m[\u001b[49m\u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnewaxis\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mpredict_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    399\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mtuple\u001b[39m(y[\u001b[38;5;241m0\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m y \u001b[38;5;129;01min\u001b[39;00m ys)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'model_1/conv2d/Relu' defined at (most recent call last):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n      self._run_once()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n      handle._run()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/home/hangdeng/.conda/envs/deeplearning-cuda11_8/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/tmp/ipykernel_31497/128668952.py\", line 4, in <module>\n      label_z = get_frame_segmentation(model,model_2D,t_idx, ch, zoom_factor,load_folder)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 119, in get_frame_segmentation\n      img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)\n    File \"/work/venkatachalamlab/Hang/GNN_matching_git/code/GNN_match/Segmentation/Video_seg.py\", line 111, in get_mask_from_proj_pred\n      img_proj_pred,_ = model_2D.predict_instances(img_proj_norm)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 777, in predict_instances\n      for r in self._predict_instances_generator(*args, **kwargs):\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 729, in _predict_instances_generator\n      for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 592, in _predict_sparse_generator\n      results = predict_direct(x)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/stardist/models/base.py\", line 398, in predict_direct\n      ys = self.keras_model.predict(x[np.newaxis], **predict_kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py\", line 321, in call\n      return self.activation(outputs)\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/activations.py\", line 321, in relu\n      return backend.relu(\n    File \"/home/hangdeng/.local/lib/python3.9/site-packages/keras/src/backend.py\", line 5397, in relu\n      x = tf.nn.relu(x)\nNode: 'model_1/conv2d/Relu'\nNo algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine eng11{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n  Profiling failure on CUDNN engine eng0{}: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16777216 bytes.\n\t [[{{node model_1/conv2d/Relu}}]] [Op:__inference_predict_function_1365]"
     ]
    }
   ],
   "source": [
    "img_proj_pred = get_mask_from_proj_pred(model_2D,img_zoom)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ddcf82cd-29de-43fc-82db-155b7f990aeb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44f87ab6-9e84-4a8d-b52d-4323246c7b0c",
   "metadata": {},
   "outputs": [],
   "source": [
    "pred, _ = model.predict_instances(img_norm*((img_proj_pred>0)), n_tiles=model._guess_n_tiles(img_norm), show_tile_progress=False)\n",
    "label_z = scipy.ndimage.zoom(pred,[1,1/zoom_factor,1/zoom_factor],order = 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f584701-eab4-47cb-a394-36fd4f349bb4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ac19836-2e82-42b2-bc8d-bd74851fc79c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7249a3a-cab8-43ed-85bf-52a88739ceb2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "82f37a1e-a4c9-48ca-947e-0e6a9a58f9a5",
   "metadata": {},
   "source": [
    "#### 4. The following version could run the above in parallel, needs to specify the memory"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "9970880e-ccbb-4dd1-8119-db19ae31be2e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# if __name__ == \"__main__\":\n",
    "#     # Define the range of iterations you want to process in parallel\n",
    "#     img_shape = get_img_shape(load_folder)\n",
    "#     [ch, zoom_factor] = [1,2] ## (for low resolution zoom_factor = 2, staticfluild use zoom_factor = 1)\n",
    "#     start_idx = 0  ## starting time index\n",
    "#     # end_idx = img_shape[0]   ## end time index\n",
    "#     end_idx = 2   \n",
    "\n",
    "#     # Create a ThreadPoolExecutor for parallel processing\n",
    "#     with concurrent.futures.ThreadPoolExecutor() as executor:\n",
    "#         # Use partial to create a function with fixed arguments (img_shape, model, model_2D, ch, zoom_factor, save_folder)\n",
    "#         process_partial = partial(process_iteration,  model=model, model_2D=model_2D, ch=ch, zoom_factor=zoom_factor, \n",
    "#                                   load_folder=load_folder, save_folder=save_folder)\n",
    "\n",
    "#         # Iterate and process in parallel using the ThreadPoolExecutor\n",
    "#         tqdm_parallel = tqdm(range(start_idx, end_idx, 1))\n",
    "#         # tqdm_parallel = tqdm(not_exits)\n",
    "#         results = list(executor.map(process_partial, tqdm_parallel))\n",
    "\n",
    "#     # Print the results (t_idx values)\n",
    "#     print(\"Processed t_idx values:\", results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8daadf5-15b0-40f8-bef8-a19c7fa9a9c0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.17"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
